[package]
name = "geoippls"
version = "0.1.0"
edition = "2024"
authors = ["Connor Hindley <conn.hindley@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { version = "0.7" }
worker-macros = { version = "0.7" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
